--Every command here will be executed when the container is created

CREATE TABLE IF NOT EXISTS mytable (
    MYID SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS mytable2 (
    MYID SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(50)
);

INSERT INTO mytable (DESCRIPTION) VALUES ('TESTE');
INSERT INTO mytable (DESCRIPTION) VALUES ('TESTE2');

CREATE TABLE CATEGORIES (
    CODE INTEGER PRIMARY KEY,
    NAME VARCHAR(255),
    TAX NUMERIC(10,2)
);

CREATE TABLE PRODUCTS (
    CODE INTEGER PRIMARY KEY,
    NAME VARCHAR(255),
    PRICE NUMERIC(10,2),
    CATEGORY INTEGER,
    FOREIGN KEY CATEGORY REFERENCES CATEGORIES(CODE)
);

CREATE TABLE ORDERS (
    CODE INTEGER PRIMARY KEY,
    TOTAL NUMERIC(10,2),
    TAX NUMERIC(10,2)
);

CREATE TABLE ORDER_ITEM(
    CODE INTEGER PRIMARY KEY,
    ORDER INTEGER,
    PRODUCT INTEGER,
    AMOUNT INTEGER,
    PRICE NUMERIC(10,2),
    TAX NUMERIC(10,2),
    FOREIGN KEY PRODUCT REFERENCES PRODUCTS(CODE),
    FOREIGN KEY ORDER REFERENCES ORDERS(CODE)
)